### PR TITLE
link added

### LINKED ISSUE #13: link van schedule & academic calendar button to backend url
link the open button on van schedule card
Screenshot 2566-08-12 at 20 00 41

to open this url  in new tab `https://center-be.stamford.dev/api/get_files/1_2023_van_schedule.pdf`

### PR DESCRIPTION
**Pull request by anascence**

### CODE REVIEW

**Review by Lxkas — CHANGES_REQUESTED** [review]
originalLink needs to point back to bb :3

**Comment by chinathaip** [comment]
> originalLink needs to point back to bb :3

bb = blackboard btw XD

**Comment by anascence** [comment]
> > originalLink needs to point back to bb :3
> 
> bb = blackboard btw XD

ohh sry :V ahoint, ahoint

**Comment by chinathaip** [comment]
Academic Calendar:
https://learn.stamford.edu/bbcswebdav/library/Library%20Content/Share%20Content/Welcome%20Page%20%28UG%29/Files/Term1-2023/1-2023_UG_Academic%20Calendar_Student%20Version_Updated%2021%20April%202023.pdf

Van Schedule:
https://learn.stamford.edu/bbcswebdav/library/Library%20Content/Share%20Content/Welcome%20Page%20%28UG%29/Files/Term1-2023/van%20schedule%20TERM%201.2023%20-%2024July%20-%2020OCT23.pdf


*ew so ugly -*-

**Comment by Lxkas** [comment]
> Academic Calendar: https://learn.stamford.edu/bbcswebdav/library/Library%20Content/Share%20Content/Welcome%20Page%20%28UG%29/Files/Term1-2023/1-2023_UG_Academic%20Calendar_Student%20Version_Updated%2021%20April%202023.pdf
> 
> Van Schedule: https://learn.stamford.edu/bbcswebdav/library/Library%20Content/Share%20Content/Welcome%20Page%20%28UG%29/Files/Term1-2023/van%20schedule%20TERM%201.2023%20-%2024July%20-%2020OCT23.pdf
> 
> _ew so ugly -_-

Let's make a URL shortener then :)

**Comment by anascence** [comment]
> shorten url, should be look like this " http://surl.li/kaepi "

**Comment by Lxkas** [comment]
Van schedule
https://learn.stamford.edu/bbcswebdav/library/Library%20Content/Share%20Content/Welcome%20Page%20%28UG%29/Files/Term1-2023/van%20schedule%20TERM%201.2023%20-%2024July%20-%2020OCT23.pdf

Term Term1-2023 Academic Calendar
https://learn.stamford.edu/bbcswebdav/library/Library%20Content/Share%20Content/Welcome%20Page%20%28UG%29/Files/Term1-2023/1-2023_UG_Academic%20Calendar_Student%20Version_Updated%2021%20April%202023.pdf

These could change, it'd be kind of annoying to keep updating them...

Also, we could just use
https://learn-ap-southeast-1-prod-fleet02-xythos.content.blackboardcdn.com/5da96a61b2455/3072688?X-Blackboard-S3-Bucket=learn-ap-southeast-1-prod-fleet02-xythos&X-Blackboard-Expiration=1691863200000&X-Blackboard-Signature=vqcnpl576PS%2FCAQsNWNzjSQKeNJkyaWTA8Mf%2Fa2s8ig%3D&X-Blackboard-Client-Id=447391

If we want to reference the bucket it's stored on, not sure if they'll delete it or not though.

**Comment by anascence** [comment]
> ...

use reverse proxy xD

**Comment by chinathaip** [comment]
or just nah, no original source? removes all complexity - for academic calendar and van schedule

**Comment by Lxkas** [comment]
That'd be kinda sad, might be better to just have it point to a scraping service :3

**Comment by Lxkas** [comment]
> Van schedule https://learn.stamford.edu/bbcswebdav/library/Library%20Content/Share%20Content/Welcome%20Page%20%28UG%29/Files/Term1-2023/van%20schedule%20TERM%201.2023%20-%2024July%20-%2020OCT23.pdf
> 
> Term Term1-2023 Academic Calendar https://learn.stamford.edu/bbcswebdav/library/Library%20Content/Share%20Content/Welcome%20Page%20%28UG%29/Files/Term1-2023/1-2023_UG_Academic%20Calendar_Student%20Version_Updated%2021%20April%202023.pdf
> 
> These could change, it'd be kind of annoying to keep updating them...
> 
> Also, we could just use https://learn-ap-southeast-1-prod-fleet02-xythos.content.blackboardcdn.com/5da96a61b2455/3072688?X-Blackboard-S3-Bucket=learn-ap-southeast-1-prod-fleet02-xythos&X-Blackboard-Expiration=1691863200000&X-Blackboard-Signature=vqcnpl576PS%2FCAQsNWNzjSQKeNJkyaWTA8Mf%2Fa2s8ig%3D&X-Blackboard-Client-Id=447391
> 
> If we want to reference the bucket it's stored on, not sure if they'll delete it or not though.

In the meantime, just change the urls to the above, we can decide what to do with it later

**Comment by anascence** [comment]
> > Van schedule https://learn.stamford.edu/bbcswebdav/library/Library%20Content/Share%20Content/Welcome%20Page%20%28UG%29/Files/Term1-2023/van%20schedule%20TERM%201.2023%20-%2024July%20-%2020OCT23.pdf
> > Term Term1-2023 Academic Calendar https://learn.stamford.edu/bbcswebdav/library/Library%20Content/Share%20Content/Welcome%20Page%20%28UG%29/Files/Term1-2023/1-2023_UG_Academic%20Calendar_Student%20Version_Updated%2021%20April%202023.pdf
> > These could change, it'd be kind of annoying to keep updating them...
> > Also, we could just use https://learn-ap-southeast-1-prod-fleet02-xythos.content.blackboardcdn.com/5da96a61b2455/3072688?X-Blackboard-S3-Bucket=learn-ap-southeast-1-prod-fleet02-xythos&X-Blackboard-Expiration=1691863200000&X-Blackboard-Signature=vqcnpl576PS%2FCAQsNWNzjSQKeNJkyaWTA8Mf%2Fa2s8ig%3D&X-Blackboard-Client-Id=447391
> > If we want to reference the bucket it's stored on, not sure if they'll delete it or not though.
> 
> In the meantime, just change the urls to the above, we can decide what to do with it later

I already added these to original links

**Comment by Lxkas** [comment]
You didn't add the short form to it, you added the versions with the tokens and whatnot
image

**Comment by chinathaip** [comment]
> You didn't add the short form to it, you added the versions with the tokens and whatnot image

ah the url gets longer when clicking on it, make sure to copy the one from here XD

van schedule:
https://learn.stamford.edu/bbcswebdav/library/Library%20Content/Share%20Content/Welcome%20Page%20%28UG%29/Files/Term1-2023/van%20schedule%20TERM%201.2023%20-%2024July%20-%2020OCT23.pdf

academic calendar:
https://learn.stamford.edu/bbcswebdav/library/Library%20Content/Share%20Content/Welcome%20Page%20%28UG%29/Files/Term1-2023/1-2023_UG_Academic%20Calendar_Student%20Version_Updated%2021%20April%202023.pdf

**Comment by anascence** [comment]
> > You didn't add the short form to it, you added the versions with the tokens and whatnot image
> 
> ah the url gets longer when clicking on it, make sure to copy the one from here XD
> 
> van schedule: https://learn.stamford.edu/bbcswebdav/library/Library%20Content/Share%20Content/Welcome%20Page%20%28UG%29/Files/Term1-2023/van%20schedule%20TERM%201.2023%20-%2024July%20-%2020OCT23.pdf
> 
> academic calendar: https://learn.stamford.edu/bbcswebdav/library/Library%20Content/Share%20Content/Welcome%20Page%20%28UG%29/Files/Term1-2023/1-2023_UG_Academic%20Calendar_Student%20Version_Updated%2021%20April%202023.pdf

ahh yes, sry, already changed it

**Comment by anascence** [comment]
> You didn't add the short form to it, you added the versions with the tokens and whatnot image

hai

**Review by Lxkas — APPROVED** [review]

**Pull request merged**
